merge_rules:
  labels:
    trigger: "mergequeue"
  preconditions:
    number_of_approvals: 1
    required_checks:
      - build
  merge_mode:
    type: "parallel"
    parallel_mode:
      max_parallel_builds: 10
      override_required_checks:
        - build
